x-group:
  x-node: &node
    restart: always
    image: louisroyer/network-debug 
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.accept_local=1
      - net.ipv4.conf.default.accept_local=1
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.all.seg6_enabled=1
      - net.ipv6.conf.default.seg6_enabled=1
    devices:
      - "/dev/net/tun:/dev/net/tun"
    volumes:
      - ../nextmn-srv6:/nextmn-srv6:ro
      - ./config:/config:ro
      - ./vol:/vol
    working_dir: /nextmn-srv6

services:
  s0:
    container_name: s0
    hostname: s0
    <<: *node
    environment:
      ROUTES_INIT: |-
        - add 10.0.103.0/24 via 10.0.101.2
      PRE_INIT_HOOK: "ip"
      PRE_INIT_HOOK_0: "addr"
      PRE_INIT_HOOK_1: "add"
      PRE_INIT_HOOK_2: "10.0.2.4/32"
      PRE_INIT_HOOK_3: "dev"
      PRE_INIT_HOOK_4: "ipv4-0"
      POST_INIT_HOOK: "ip"
      POST_INIT_HOOK_0: "route"
      POST_INIT_HOOK_1: "del"
      POST_INIT_HOOK_2: "default"

    networks:
      ipv4-service-backbone:
        ipv4_address: 10.0.101.4
  s1:
    container_name: s1
    hostname: s1
    <<: *node
    environment:
      ROUTES_INIT: |-
        - add 10.0.103.0/24 via 10.0.101.3
      PRE_INIT_HOOK: "ip"
      PRE_INIT_HOOK_0: "addr"
      PRE_INIT_HOOK_1: "add"
      PRE_INIT_HOOK_2: "10.0.2.4/32"
      PRE_INIT_HOOK_3: "dev"
      PRE_INIT_HOOK_4: "ipv4-0"
      POST_INIT_HOOK: "ip"
      POST_INIT_HOOK_0: "route"
      POST_INIT_HOOK_1: "del"
      POST_INIT_HOOK_2: "default"
    networks:
      ipv4-service-backbone:
        ipv4_address: 10.0.101.5
  r:
    container_name: rr
    hostname: r
    <<: *node
    networks:
      ipv6-backbone:
        ipv6_address: fd00:1111:2222:3333:4444::2
  r0:
    container_name: r0
    hostname: r0
    <<: *node
    environment:
      ROUTES_INIT: |-
        - add 10.0.2.0/24 via 10.0.101.4
    networks:
      ipv6-backbone:
        ipv6_address: fd00:1111:2222:3333:4444::3
      ipv4-service-backbone:
        ipv4_address: 10.0.101.2
  r1:
    container_name: r1
    hostname: r1
    <<: *node
    environment:
      ROUTES_INIT: |-
        - add 10.0.2.0/24 via 10.0.101.5
    networks:
      ipv6-backbone:
        ipv6_address: fd00:1111:2222:3333:4444::4
      ipv4-service-backbone:
        ipv4_address: 10.0.101.3
  srgw:
    container_name: srgw
    hostname: srgw
    <<: *node
    networks:
      ipv6-backbone:
        ipv6_address: fd00:1111:2222:3333:4444::1
      gtp4:
        ipv4_address: 10.0.102.3
  gnb:
    container_name: gnb
    hostname: gnb
    <<: *node
    environment:
      POST_INIT_HOOK: "ip"
      POST_INIT_HOOK_0: "route"
      POST_INIT_HOOK_1: "del"
      POST_INIT_HOOK_2: "default"
    networks:
      ran:
        ipv4_address: 10.0.103.2
      gtp4:
        ipv4_address: 10.0.102.2
  ue1:
    container_name: ue1
    hostname: ue1
    <<: *node
    environment:
      ROUTES_INIT: |-
        - add 10.0.2.0/24 via 10.0.103.2
      POST_INIT_HOOK: "ip"
      POST_INIT_HOOK_0: "route"
      POST_INIT_HOOK_1: "del"
      POST_INIT_HOOK_2: "default"
    networks:
      ran:
        ipv4_address: 10.0.103.3
  ue2:
    container_name: ue2
    hostname: ue2
    <<: *node
    environment:
      ROUTES_INIT: |-
        - add 10.0.2.0/24 via 10.0.103.2
      POST_INIT_HOOK: "ip"
      POST_INIT_HOOK_0: "route"
      POST_INIT_HOOK_1: "del"
      POST_INIT_HOOK_2: "default"
    networks:
      ran:
        ipv4_address: 10.0.103.4
    
  
networks:
  ipv6-backbone:
    enable_ipv6: true
    name: ipv6-backbone 
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: ipv6-backbone 
      com.docker.network.container_iface_prefix: ipv6- 
    ipam:
      driver: default
      config:
        - subnet: 10.0.100.0/24
        - subnet: fd00:1111:2222:3333:4444::/80
          ip_range: fd00:1111:2222:3333:4444:8000::/81
          gateway: fd00:1111:2222:3333:4444::fffe
  ran:
    enable_ipv6: false
    name: sr-domain
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: ran
      com.docker.network.container_iface_prefix: ran- 
    ipam:
      driver: default
      config:
        - subnet: 10.0.103.0/24
  
  ipv4-service-backbone:
    enable_ipv6: false
    name: ipv6-service-backbone 
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: ipv4-backbone 
      com.docker.network.container_iface_prefix: ipv4- 
    ipam:
      driver: default
      config:
        - subnet: 10.0.101.0/24
  gtp4:
    enable_ipv6: false
    name:  gtp4
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: gtp4 
      com.docker.network.container_iface_prefix: gtp4- 
    ipam:
      driver: default
      config:
        - subnet: 10.0.102.0/24
