debug: true
ipv4-headend-prefix: "10.0.2.0/24" # handle packets with this destination
linux-headend-set-source-address: "fd00:2222:0001:0A00:6602:04D2::0030" # fd00:2222:1::/48 + 10.0.102.2 port 1234
headends:
  - name: "simulate gnb uplink"
    to: "10.0.2.0/24"
    provider: "Linux"
    behavior: "H.Encaps"
    policy:
      - bsid:
          segments-list:
            - "fd00:2222:1:0A00:6603:0000:0000:0100" # to 10.0.102.3 TEID 1 = 0A 00 66 03 |00| 00 00 00 01

locator: "fd00:2222::/32"
endpoints:
  - prefix: "fd00:2222:1::/48"
    provider: "NextMN"
    behavior: "End.M.GTP4.E"
